//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayerProject.PatientLookUp1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PatientLookUp1.LookUpService")]
    public interface LookUpService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LookUpService/RetrievePatientInformation", ReplyAction="http://tempuri.org/LookUpService/RetrievePatientInformationResponse")]
        System.Data.DataSet RetrievePatientInformation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LookUpService/RetrievePatientInformation", ReplyAction="http://tempuri.org/LookUpService/RetrievePatientInformationResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> RetrievePatientInformationAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LookUpServiceChannel : BusinessLayerProject.PatientLookUp1.LookUpService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LookUpServiceClient : System.ServiceModel.ClientBase<BusinessLayerProject.PatientLookUp1.LookUpService>, BusinessLayerProject.PatientLookUp1.LookUpService {
        
        public LookUpServiceClient() {
        }
        
        public LookUpServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LookUpServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LookUpServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LookUpServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet RetrievePatientInformation() {
            return base.Channel.RetrievePatientInformation();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> RetrievePatientInformationAsync() {
            return base.Channel.RetrievePatientInformationAsync();
        }
    }
}
